### ISSUE TITLE
予算とか

### ISSUE THREAD

**Issue by 27Cobalter** [DRAFTS-I/conference#1]
物によっては学科が出してくれるっぽい
予算がふえるよ　~~やったねたえちゃん~~

**Comment by KondoTakumi** [comment]
物によっては学科が出してくれるっぽい
予算がふえるよ　やったねたえちゃん

**Comment by 27Cobalter** [comment]
必要材料ってここに一緒に書く感じでいいかね？新しく作ったほうがいいかな？

**Comment by uratoss** [comment]
ここに書いても問題は無いと思う
