### ISSUE TITLE
ロボットのデザイン

### ISSUE THREAD

**Issue by uratoss** [DRAFTS-I/conference#10]
ロボットのデザイン(メインコンセプト)について

**Comment by S-Terada** [comment]
現状だとエレクトリック・パンク(？)路線

**Comment by uratoss** [comment]
もしくはヒルドルブ（MS IGLOOより）のようなガチタン兵器路線

v 参考までに
http://dic.pixiv.net/a/ヒルドルブ

**Comment by S-Terada** [comment]
ガチタン路線だとアタッチメントの付け替えが似合わない気がするけどどう？

**Comment by uratoss** [comment]
どうだろう…イメージ的に武器のパージとか結構する気がしたから問題ないかなーって

**Comment by S-Terada** [comment]
凄い個人的な思いで申し訳ないけど戦車がパージする事に違和感を持ったから聞いてみた
(履帯をパージする超重戦車のイメージが浮かんだ)

**Comment by uratoss** [comment]
そういわれると確かに違和感はあるね...ロボットの移動方法が8輪かクローラーになってたからそれに似合うデザインがガチタン路線が無難かなって考えてた

**Comment by uratoss** [comment]
ガチタン路線とか色々考えたけど、設計・作業難易度的に考えてフル武装R2D2が良い気がしたんだけどどうかな？アイツ確かクローラー移動だし

**Comment by 27Cobalter** [comment]
![desktop 03 31 2017 - 22 52 20 01](https://cloud.githubusercontent.com/assets/24519665/24553314/d90f0b3a-1664-11e7-84c1-f1b585e020df.png)
