### ISSUE TITLE
制御プログラムの設計

### ISSUE THREAD

**Issue by uratoss** [DRAFTS-I/conference#14]
各回路などの制御をどのようにするのか？

**Comment by 27Cobalter** [comment]
# RaspberryPiとArduinoの通信フォーマット

## ディジタル入力

|1byte|2byte|3byte|4byte|
|:----|:----|:----|:----|
|0x80 (start bit)|○×△□↑↓→←|R1,R2,L1,L2,START,SELECT,\[mode\](2bit)|パリティ|

パリティ
`(1+2+3)&0x3f`

## アナログ入力

|1byte|2byte|3byte|4byte|5byte|6byte|7byte|8byte|
|:----|:----|:----|:----|:----|:----|:----|:----|
|0xC0 (start bit)|R2|L2|Lx|Ly|Rx|Ry|パリティ|


パリティ
`(1+2+3+4+5+6+7)&0x3f`
